apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-ipv6
spec:
  properties:
    - "java.net.preferIPv4Stack": "false"
    - "java.net.preferIPv6Addresses": "true"
    - "hazelcast.prefer.ipv4.stack": "false"
