apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: mancenter
spec:
  hazelcastClusters:
    - address: hazelcast
      name: dev
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

