apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: managementcenter
spec:
  repository: "hazelcast/management-center"
  licenseKeySecretName: hazelcast-license-key
  externalConnectivity:
    type: ClusterIP
    ingress:
      hostname: "example.hostname"
      ingressClassName: nginx
      path: "/mancenter"
      annotations:
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
  hazelcastClusters:
    - address: hazelcast
      name: dev
