apiVersion: hazelcast.com/v1alpha1
kind: CronHotBackup
metadata:
  name: cronhotbackup
spec:
  schedule: "* * * * *"
  hotBackupTemplate:
    metadata:
      labels:
        cron-hotbackup: "true"
    spec:
      hazelcastResourceName: hazelcast